package evidencelogger.domain;

/** Event types required by the approved transition table. */
public enum AuditEventType {
    CASE_CREATED,
    CASE_ASSIGNED,
    CASE_UNASSIGNED,
    LOCATION_ADDED,
    EVIDENCE_REGISTERED,
    REQUEST_SUBMITTED,
    REQUEST_WITHDRAWN,
    REQUEST_APPROVED,
    REQUEST_REJECTED,
    REQUEST_CANCELLED,
    HANDOFF_RECORDED,
    HANDOFF_REVERSED,
    COLLECTION_ACKNOWLEDGED,
    EXAMINATION_NOTE_ADDED,
    RETURN_INITIATED,
    RETURN_INSPECTED_STORED,
    RETURN_INSPECTED_HELD,
    UNPLANNED_RETURN_INSPECTED,
    HISTORY_CORRECTED,
    EXAMINATION_NOTE_CORRECTED
}
