name: MarkBind Action

on:
  push:
    branches:
      - master
      - markbind

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'zulu'
      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          package-manager-cache: false
      - name: Install MarkBind
        run: npm install --global markbind-cli@6.0.2
      - name: Build MarkBind site
        run: markbind build docs _site --baseUrl /CS3227-2610-MP2
      - name: Deploy MarkBind site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
